name: Tamil WhatsApp Calendar

on:
  schedule:
    - cron: "30 0 * * *"    # 06:00 AM IST (00:30 UTC)
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install requests
      run: pip install requests

    - name: Send WhatsApp Messages
      env:
        WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
        PHONE_NUMBER_ID: ${{ secrets.PHONE_NUMBER_ID }}
        RECIPIENT_NUMBERS: ${{ secrets.RECIPIENT_NUMBERS }}
      run: python send_calendar.py
